### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by InfernalDread** [Josh-XT/Agent-LLM#1]
I am getting this error after running "python main.py [objective typed here]"

The error is stemming from commands.py on line 17 in the main directory of this repo.

I am not sure what the solution is.

Here is the code output:

(venv) C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM>python main.py "find information on what is ChatGPT"
Using embedded DuckDB with persistence: data will be stored in: memories

*****OBJECTIVE*****

find information on what is ChatGPT

Initial task: Develop a task list
Traceback (most recent call last):
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\main.py", line 14, in <module>
    main(args.primary_objective)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\main.py", line 7, in main
    tms.run()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\babyagi.py", line 105, in run
    task = self.execute_next_task()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\babyagi.py", line 84, in execute_next_task
    self.response = self.execution_agent(self.primary_objective, task["task_name"])
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\babyagi.py", line 72, in execution_agent
    self.response = self.prompter.run(prompt)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\AgentLLM.py", line 59, in run
    commands_prompt = self.commands.get_prompt()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\Commands.py", line 35, in get_prompt
    self.commands = self.load_commands()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\Commands.py", line 17, in load_commands
    if issubclass(module.__dict__.get(module_name), Commands):
TypeError: issubclass() arg 1 must be a class

**Comment by Josh-XT** [comment]
Updated, should be fixed now.

**Comment by InfernalDread** [comment]
That's great! Will test now!

**Comment by InfernalDread** [comment]
> Updated, should be fixed now.

New issue, I am getting this error: ModuleNotFoundError: No module named 'playsound'

I tried to install it with pip, but that wouldn't work either.
