### ISSUE TITLE
BARD issue

### ISSUE THREAD

**Issue by gururise** [Josh-XT/Agent-LLM#104]
AI_PROVIDER=bard
AI_MODEL=bard
AI_TEMPERATURE=0.1
MAX_TOKENS=2096
BARD_TOKEN=..my token here..

results in the following error:
```
Using embedded DuckDB with persistence: data will be stored in: agents/Agent-LLM/memories
INFO:     127.0.0.1:55920 - "POST /api/agent/Agent-LLM/instruct HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/gene/Downloads/Agent-LLM/app.py", line 125, in instruct
    agent = AgentLLM(agent_name)
  File "/home/gene/Downloads/Agent-LLM/AgentLLM.py", line 48, in __init__
    self.ai_instance = ai_module.AIProvider()
  File "/home/gene/Downloads/Agent-LLM/provider/bard.py", line 10, in __init__
    self.chatbot = Chatbot(CFG.BARD_TOKEN)
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/Bard.py", line 85, in __init__
    self.SNlM0e = self.__get_snlm0e()
  File "/home/gene/Downloads/Agent-LLM/venv/lib/python3.10/site-packages/Bard.py", line 92, in __get_snlm0e
    SNlM0e = re.search(r"SNlM0e\":\"(.*?)\"", resp.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Josh-XT** [comment]
Hello!  We use this module for Bard -> https://github.com/acheong08/Bard

The error you're seeing is coming from that module because it is not getting a response.
