### ISSUE TITLE
Oobabooga and llamacpp fail to run after loading "main/app.py" and "npm start", using venv on windows 10

### ISSUE THREAD

**Issue by InfernalDread** [Josh-XT/Agent-LLM#11]
The website looks amazing! I am trying to run this with Oobabooga API, everything was looking good, but this error was sent to me after I used the website to run an objective.

I also tried llamacpp, but also ran into errors in the same situation.

Here is the error for Oobabooga:

(venv) C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM>python main.py
Using embedded DuckDB with persistence: data will be stored in: memories/Agent-LLM
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
Using embedded DuckDB with persistence: data will be stored in: memories/Agent-LLM
 * Debugger is active!
 * Debugger PIN: 737-166-586
127.0.0.1 - - [18/Apr/2023 18:41:37] "GET /api/docs/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:41:37] "GET /api/docs/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:41:37] "GET /api/get_agents HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:41:38] "GET /api/get_commands HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:41:43] "OPTIONS /api/delete_agent/My-Agent-Name HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:41:43] "DELETE /api/delete_agent/My-Agent-Name HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:41:43] "GET /api/get_agents HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:41:56] "OPTIONS /api/set_objective HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:41:56] "POST /api/set_objective HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:41:57] "GET /api/execute_next_task HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Mike's PC\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Mike's PC\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Mike's PC\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\app.py", line 105, in get
    task = babyagi_instance.execute_next_task()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\babyagi.py", line 135, in execute_next_task
    self.response = self.execution_agent(self.primary_objective, task["task_name"])
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\babyagi.py", line 112, in execution_agent
    self.response = self.prompter.run(prompt)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\AgentLLM.py", line 61, in run
    self.response = self.instruct(f"{commands_prompt}\n{prompt}")
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\provider\oobabooga.py", line 20, in instruct
    return response.json()['data'][0].replace("\n", "\n")
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

--------------------------------------------------------------------------------------------------------------------------------------------------

Here is the error for llamacpp

(venv) C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM>python main.py
Using embedded DuckDB with persistence: data will be stored in: memories/Agent-LLM
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
Using embedded DuckDB with persistence: data will be stored in: memories/Agent-LLM
 * Debugger is active!
 * Debugger PIN: 737-166-586
127.0.0.1 - - [18/Apr/2023 18:47:00] "GET /api/docs/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:47:00] "GET /api/docs/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:47:00] "GET /api/get_agents HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:47:01] "GET /api/get_commands HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:47:20] "OPTIONS /api/set_objective HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:47:20] "POST /api/set_objective HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 18:47:20] "GET /api/execute_next_task HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\app.py", line 105, in get
    task = babyagi_instance.execute_next_task()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\babyagi.py", line 135, in execute_next_task
    self.response = self.execution_agent(self.primary_objective, task["task_name"])
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\babyagi.py", line 112, in execution_agent
    self.response = self.prompter.run(prompt)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\AgentLLM.py", line 61, in run
    self.response = self.instruct(f"{commands_prompt}\n{prompt}")
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\provider\llamacpp.py", line 8, in instruct
    llama_path = CFG.LLAMACPP_PATH if CFG.LLAMACPP_PATH else "llama/main"
AttributeError: 'Config' object has no attribute 'LLAMACPP_PATH'

**Comment by InfernalDread** [comment]
After entering an objective while using oobabooga as provider, I got this error:


(venv) C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM>python main.py
Using embedded DuckDB with persistence: data will be stored in: memories/Agent-LLM
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
Using embedded DuckDB with persistence: data will be stored in: memories/Agent-LLM
 * Debugger is active!
 * Debugger PIN: 737-166-586
127.0.0.1 - - [18/Apr/2023 19:22:02] "GET /api/docs/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 19:22:02] "GET /api/docs/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 19:22:02] "GET /api/get_agents HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 19:22:03] "GET /api/get_commands HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 19:22:29] "OPTIONS /api/set_objective HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 19:22:29] "POST /api/set_objective HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2023 19:23:29] "GET /api/execute_next_task HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Mike's PC\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Mike's PC\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Mike's PC\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\app.py", line 105, in get
    task = babyagi_instance.execute_next_task()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\babyagi.py", line 135, in execute_next_task
    self.response = self.execution_agent(self.primary_objective, task["task_name"])
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\babyagi.py", line 112, in execution_agent
    self.response = self.prompter.run(prompt)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\AgentLLM.py", line 61, in run
    self.response = self.instruct(f"{commands_prompt}\n{prompt}")
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\provider\oobabooga.py", line 20, in instruct
    return response.json()['data'][0].replace("\n", "\n")
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
