### ISSUE TITLE
Issue when connecting "npm start" to "python app.py" (venv windows 10)

### ISSUE THREAD

**Issue by InfernalDread** [Josh-XT/Agent-LLM#13]
First I launched "python app.py", then on another terminal "npm start", everything began connecting, but this error appeared:

(venv) C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM>python app.py
Using embedded DuckDB with persistence: data will be stored in: memories/Agent-LLM
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
Using embedded DuckDB with persistence: data will be stored in: memories/Agent-LLM
 * Debugger is active!
 * Debugger PIN: 737-166-586
127.0.0.1 - - [19/Apr/2023 00:01:22] "GET /api/docs/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2023 00:01:22] "GET /api/docs/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2023 00:01:22] "GET /api/get_agents HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2023 00:01:27] "GET /api/get_commands HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\app.py", line 134, in get
    commands_list = commands.get_commands_list()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\Commands.py", line 56, in get_commands_list
    self.commands = self.load_commands()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\Commands.py", line 20, in load_commands
    for command_name, command_function in command_class.commands.items():
AttributeError: 'microsoft_365_email' object has no attribute 'commands'

**Comment by InfernalDread** [comment]
the commands list also disappeared

**Comment by Josh-XT** [comment]
Try to pull the latest and see if you're still having issues.
