### ISSUE TITLE
pip install -r "requirements.txt"

### ISSUE THREAD

**Issue by WillTryToDoItRight** [Josh-XT/Agent-LLM#139]
### Title

When installing the requirements - error on playground

### Description

Collecting playsound (from -r requirements.txt (line 22))
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/home/g3n3r3luser/Programming/Agent-LLM/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/g3n3r3luser/Programming/Agent-LLM/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/g3n3r3luser/Programming/Agent-LLM/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ml2jsas5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ml2jsas5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ml2jsas5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-ml2jsas5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "/usr/lib/python3.10/inspect.py", line 1147, in getsource
          lines, lnum = getsourcelines(object)
        File "/usr/lib/python3.10/inspect.py", line 1129, in getsourcelines
          lines, lnum = findsource(object)
        File "/usr/lib/python3.10/inspect.py", line 958, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.

### Steps to Reproduce

1. Delete everything. because I tried to clone it again... #119
2. on linux: python3 -m venv .venv
3. source ./.venv/bin/activate
4. python3 -m install --upgrade pip
5. pip install -r "requirements.txt"

Playsound dependencies is somehow broken

### Expected Behavior

go through it complete.

### Actual Behavior

breaks on playsound

### Additional Context

VM Ubuntu
Agent-LLM V1.0.14

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet
- [X] I am using the latest version of the software
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue

**Comment by Josh-XT** [comment]
If you're also using conda, please do this:
```
conda install --file requirements.txt
```

**Comment by Josh-XT** [comment]
> pygobject

Try `pip install playsound==1.2.2`, I also just updated the requirement in #163.

**Comment by WillTryToDoItRight** [comment]
downgraded from 1.3 to 1.2.2
error message is gone now.
