### ISSUE TITLE
Provider: ChatGPT issues in Chrome

### ISSUE THREAD

**Issue by InfernalDread** [Josh-XT/Agent-LLM#15]
I have the credentials on .env, but here is the error code:

(venv) C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM>python app.py
Using embedded DuckDB with persistence: data will be stored in: memories/Agent-LLM
Traceback (most recent call last):
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\app.py", line 17, in <module>
    babyagi_instance = babyagi()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\babyagi.py", line 45, in __init__
    self.prompter = AgentLLM()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\AgentLLM.py", line 36, in __init__
    self.ai_instance = ai_module.AIProvider()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\provider\chatgpt.py", line 25, in __init__
    self.browser = uc.Chrome(options=options)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\undetected_chromedriver\__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\undetected_chromedriver\__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:57382
from unknown error: unable to discover open pages
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0026DCE3+50899]
        (No symbol) [0x001FE111]
        (No symbol) [0x00105588]
        (No symbol) [0x001255A9]
        (No symbol) [0x0011F5B1]
        (No symbol) [0x0011F391]
        (No symbol) [0x00151FFE]
        (No symbol) [0x00151CEC]
        (No symbol) [0x0014B6F6]
        (No symbol) [0x00127708]
        (No symbol) [0x0012886D]
        GetHandleVerifier [0x004D3EAE+2566302]
        GetHandleVerifier [0x005092B1+2784417]
        GetHandleVerifier [0x0050327C+2759788]
        GetHandleVerifier [0x00305740+672048]
        (No symbol) [0x00208872]
        (No symbol) [0x002041C8]
        (No symbol) [0x002042AB]
        (No symbol) [0x001F71B7]
        BaseThreadInitThunk [0x771F0099+25]
        RtlGetAppContainerNamedObjectPath [0x77DB7B6E+286]
        RtlGetAppContainerNamedObjectPath [0x77DB7B3E+238]
        (No symbol) [0x00000000]

(venv) C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM>

**Comment by TroublesInParadise** [comment]
Same here. I have tried switching to ooba llama but the first command immediately uses 3000 tokens.

**Comment by Josh-XT** [comment]
I'm not sure if the ChatGPT one works or not. I'll do some testing with it. I may use a different module for connecting to that.

**Comment by JamesonRGrieve** [comment]
Closing due to ChatGPT automation safeguards preventing selenium from working properly. Will re-explore in the future.
