### ISSUE TITLE
HuggingChat Error

### ISSUE THREAD

**Issue by timuryunuk2023** [Josh-XT/Agent-LLM#169]
### Description

With new version it says that it cannot deserialize json body
Status code: 422
Response content: b'Failed to deserialize the JSON body into the target type: parameters.max_new_tokens: invalid value: integer `-1380`, expected u32 at line 1 column 4229'
Exception in thread Thread-2 (run_task):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/timur/Downloads/Agent-LLM-1.0.17-alpha/AgentLLM.py", line 330, in run_task
    result = self.execution_agent(task["task_name"], task["task_id"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-1.0.17-alpha/AgentLLM.py", line 313, in execution_agent
    return self.run(prompt)
           ^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-1.0.17-alpha/AgentLLM.py", line 119, in run
    self.response = self.instruct(prompt)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-1.0.17-alpha/provider/huggingchat.py", line 44, in instruct
    raise Exception("Failed to send prompt to AI")
Exception: Failed to send prompt to AI

.env file
AI_PROVIDER=huggingchat
AI_MODEL=openassistant
AI_TEMPERATURE=0.2
MAX_TOKENS=2048

### Steps to Reproduce the Bug

Create .env file with huggingface as AI provider
Start backend
Start frontend
Set agent objective

### Expected Behavior

Start the task execution

### Actual Behavior

Gives "Failed to send message" error

### Operating System

- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Please pull latest, just fixed and tested this.

**Comment by timuryunuk2023** [comment]
Thank you very much. Will test when reach home.
