### ISSUE TITLE
Backend Exits Immediately

### ISSUE THREAD

**Issue by TheRealPhooney** [Josh-XT/Agent-LLM#171]
### Description

After setting up 1.0.18 and running "docker compose up -d"  The frontend and backend start on docker, but the backend seems to exit immediately.

### Steps to Reproduce the Bug

1. Instal 1.0.18 as per instructions and run the "docker compose up -d" command
2. When you look at Docker, see that backend has exited.

### Expected Behavior

Expected frontend and backend to be running so I could open up the agent-llm interface in a browser.

### Actual Behavior

Here is the log from the Docker backend:

2023-04-30 04:04:47 Traceback (most recent call last):
2023-04-30 04:04:47   File "/usr/local/bin/uvicorn", line 8, in <module>
2023-04-30 04:04:47     sys.exit(main())
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
2023-04-30 04:04:47     return self.main(*args, **kwargs)
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
2023-04-30 04:04:47     rv = self.invoke(ctx)
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
2023-04-30 04:04:47     return ctx.invoke(self.callback, **ctx.params)
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
2023-04-30 04:04:47     return __callback(*args, **kwargs)
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 403, in main
2023-04-30 04:04:47     run(
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 568, in run
2023-04-30 04:04:47     server.run()
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 59, in run
2023-04-30 04:04:47     return asyncio.run(self.serve(sockets=sockets))
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
2023-04-30 04:04:47     return loop.run_until_complete(main)
2023-04-30 04:04:47   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 66, in serve
2023-04-30 04:04:47     config.load()
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 471, in load
2023-04-30 04:04:47     self.loaded_app = import_from_string(self.app)
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
2023-04-30 04:04:47     module = importlib.import_module(module_str)
2023-04-30 04:04:47   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2023-04-30 04:04:47     return _bootstrap._gcd_import(name[level:], package, level)
2023-04-30 04:04:47   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2023-04-30 04:04:47   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2023-04-30 04:04:47   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2023-04-30 04:04:47   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2023-04-30 04:04:47   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2023-04-30 04:04:47   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2023-04-30 04:04:47   File "/app/app.py", line 72, in <module>
2023-04-30 04:04:47     async def add_agent(agent_name: AgentName) -> dict[str, str]:
2023-04-30 04:04:47 TypeError: 'type' object is not subscriptable

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
A lot of back end changes were done over the past week in the branch that we just merged for v1.1.0-alpha.  Please try it and create an issue if ongoing.
