### ISSUE TITLE
Backend / saving whole objective as filename in textfile

### ISSUE THREAD

**Issue by WillTryToDoItRight** [Josh-XT/Agent-LLM#173]
### Description

So I gave GPT4 a rather long objective (250 words)

### Steps to Reproduce the Bug

1. open .env / set model to gpt-4
2. localhost:3000 / go to agent LLM objective
3. enter 250 token text with { things } and (stuff)
4. get error as seen above

### Expected Behavior

After clicking the button, I would expect that the agent starts doing the tasks.

### Actual Behavior

and get this result:
Exception in thread Thread-2 (run_task):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/Agent-LLM/AgentLLM.py", line 311, in run_task
    self.update_output_list(
  File "/home/xxxAgent-LLM/AgentLLM.py", line 245, in update_output_list
    self.CFG.save_task_output(self.agent_name, output, self.primary_objective)
  File "/home/xxx/Agent-LLM/Config.py", line 350, in save_task_output
    with open(
OSError: [Errno 36] File name too long: 'agents/Agent-LLM/tasks/You are F[250 WORDS LONG OBJECTIVE]. .txt

INFO:     127.0.0.1:57610 - "GET /api/agent/Agent-LLM/task/status HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/gxxx/Agent-LLM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/xxx/Agent-LLM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/xxx/Agent-LLM/app.py", line 241, in get_task_status
    status = CFG.agent_instances[agent_name].get_status()
  File "/home/xxx/Agent-LLM/AgentLLM.py", line 238, in get_status
    return not self.stop_running_event.is_set()
AttributeError: 'NoneType' object has no attribute 'is_set'

### Additional Context / Screenshots

Linux on VM from Windows
Agent-LLM v1.0.17-alpha

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Currently working as intended.  This will change in a future update when we switch from being file based to putting all of this in a database.
