### ISSUE TITLE
HuggingChat error

### ISSUE THREAD

**Issue by timuryunuk2023** [Josh-XT/Agent-LLM#175]
### Description

after update it's even more errors
Exception in thread Thread-2 (run_task):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/timur/Downloads/Agent-LLM-main/AgentLLM.py", line 333, in run_task
    result = self.execution_agent(task["task_name"], task["task_id"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-main/AgentLLM.py", line 316, in execution_agent
    return self.run(prompt)
           ^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-main/AgentLLM.py", line 119, in run
    self.response = self.instruct(prompt)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-main/provider/huggingchat.py", line 41, in instruct
    data = res.json()
           ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

.env
AI_PROVIDER=huggingchat
AI_MODEL=openassistant
AI_TEMPERATURE=0.2
MAX_TOKENS=2048
prompt: Write a tweet about ai
### Steps to Reproduce the Bug

Create .env file with huggingface as AI provider
Start backend
Start frontend
Set agent objective

### Expected Behavior

Start the task execution

### Actual Behavior

Falls with error

### Operating System

- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Should be fixed with v1.1.0-alpha
