### ISSUE TITLE
Error when go to agent

### ISSUE THREAD

**Issue by timuryunuk2023** [Josh-XT/Agent-LLM#182]
### Description

In new version there is an error when user go to agent page (http://localhost:3000/agent/Agent-LLM)

<img width="1264" alt="Знімок екрана 2023-05-01 о 22 44 06" src="https://user-images.githubusercontent.com/90114599/235536937-6909115f-e8ef-40fa-930f-c9c01ad1f9d5.png">

Promise { <pending> }
error - unhandledRejection: Error: connect ECONNREFUSED ::1:80
    at AxiosError.from (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}
error - Error: connect ECONNREFUSED ::1:80
    at AxiosError.from (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}
error - Error: connect ECONNREFUSED ::1:80
    at AxiosError.from (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}

### Steps to Reproduce the Bug

1. Run frontend
2. Run backend
3. Go to http://localhost:3000/agent/Agent-LLM 

### Expected Behavior

Goes to page without error

### Actual Behavior

Error occurs

### Operating System

- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by samuzaffar99** [comment]
Search for: await axios.get(`/api/provider`)
and replace with: axios.get(`${process.env.NEXT_PUBLIC_API_URI ?? 'http://localhost:7437'}/api/provider`)

**Comment by jeffwadsworth** [comment]
What file is this "axios.get('/api/provider') located in?

**Comment by samuzaffar99** [comment]
- frontend/components/systems/agent/tabs/AgentConfigure.js
- frontend/pages/provider/[provider].js
- frontend/pages/provider/index.js

**Comment by jeffwadsworth** [comment]
Sadly, the same error comes up.

**Comment by kenfink** [comment]
frontend/pages/api/provider/index.js
line 16 change:
        await axios.get(`${process.env.API_URI}/api/provider`).then((response) => {
to
	await axios.get(`${process.env.NEXT_PUBLIC_API_URI}/api/provider`).then((response) => {

Not sure how to create a PR for this.  First timer!
