### ISSUE TITLE
"PATCH /api/agent/Bob/command HTTP/1.1" 500 Internal Server Error

### ISSUE THREAD

**Issue by Copterz** [Josh-XT/Agent-LLM#186]
### Description

When I click any of the command buttons, nothing happens. Can't turn any commands on for the agent. Error is: "PATCH /api/agent/Bob/command HTTP/1.1" 500 Internal Server Error

### Steps to Reproduce the Bug

1. Goto agent page
2. Click on 'All Commands' or any other command.

### Expected Behavior

Commands should be enabled.

### Actual Behavior

Error shows in the command window that where you run python app.py

### Additional Context / Screenshots

Used this a couple of days ago, and almost had it working, well at least the commands were enabled. now it seems to be even worse. Also, the axios errors are still everywhere. 

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Please pull the latest and let us know if you're still having issues.

https://github.com/Josh-XT/Agent-LLM/releases/tag/v1.1.1-alpha

**Comment by Copterz** [comment]
Seems more stable, less errors popping up, but still getting the same error whenever I click on any of the command enable buttons: "PATCH /api/agent/JoeyB/command HTTP/1.1" 500 Internal Server Error

A bit more info from the frontend:

error - unhandledRejection: Error: connect ECONNREFUSED ::1:7437
    at AxiosError.from (file:///E:/AI/TCHT/oobabooga_windows/Agent-LLM/frontend/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///E:/AI/TCHT/oobabooga_windows/Agent-LLM/frontend/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (E:\AI\TCHT\oobabooga_windows\Agent-LLM\frontend\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}

**Comment by Josh-XT** [comment]
Just committed updates to main that resolve this.
