### ISSUE TITLE
Request failed with status code 404 when using oobabooga

### ISSUE THREAD

**Issue by Setmaster** [Josh-XT/Agent-LLM#193]
### Description

When I open the app's page at http://localhost:3000/ and click the providers list, I can see the provider "chatgptfastchatopenikoboldllama..." (maybe this name is already an error?) if I click on it I get the error code 404. Attempting to use it for an agent results in the agent giving the same error.

### Steps to Reproduce the Bug

Git clone repo
Setup .env like [this](https://gist.github.com/Setmaster/26341ff280dce31a2d66f03e58bc3042)
Run docker compose up -d
Go to providers page or agent and try using the "chatgptfastchatopen..." option

### Expected Behavior

oobagooga can be used correctly without 404 errors

### Actual Behavior

Both provider and agent page give 404 errors if the user interacts with the "chatgptfastchat..." option

### Additional Context / Screenshots

Windows 10
Using docker 4.19 with WSL 2 backend for Agent-LLM
Oobagooga is running in a conda env in wsl 2
`Starting streaming server at ws://127.0.0.1:5005/api/v1/stream
Starting API at http://127.0.0.1:5000/api
Running on local URL:  http://127.0.0.1:7861`

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Please pull the latest and let us know if you're still having issues.

https://github.com/Josh-XT/Agent-LLM/releases/tag/v1.1.1-alpha

**Comment by Setmaster** [comment]
Problem persists.
Ooba Log:
```
127.0.0.1 - - [03/May/2023 13:31:21] "GET /api/v1/model HTTP/1.1" 200 -
```
Agent backend log:
```
2023-05-03 13:31:01 INFO:     172.21.0.1:47300 - "GET /api/provider HTTP/1.1" 200 OK
```
Agent frontend log:
```
2023-05-03 14:01:07 Promise { <pending> }
2023-05-03 14:01:07 (node:29) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80
2023-05-03 14:01:07     at Function.AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
2023-05-03 14:01:07     at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:591:25)
2023-05-03 14:01:07     at RedirectableRequest.emit (events.js:400:28)
2023-05-03 14:01:07     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
2023-05-03 14:01:07     at ClientRequest.emit (events.js:400:28)
2023-05-03 14:01:07     at Socket.socketErrorListener (_http_client.js:475:9)
2023-05-03 14:01:07     at Socket.emit (events.js:400:28)
2023-05-03 14:01:07     at emitErrorNT (internal/streams/destroy.js:106:8)
2023-05-03 14:01:07     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
2023-05-03 14:01:07     at processTicksAndRejections (internal/process/task_queues.js:82:21)
2023-05-03 14:01:07 (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
```

**Comment by shaiss** [comment]
I cant add any agents or do anything with the app. I pulled the latest codebase and get this same error 
```
2023-05-10 11:33:52     at processTicksAndRejections (internal/process/task_queues.js:82:21)
2023-05-10 11:33:52 (Use `node --trace-warnings ...` to show where the warning was created)
2023-05-10 11:33:52 (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
2023-05-10 11:33:52 (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Any suggestions?

**Comment by qrekkwijjtx54** [comment]
> I cant add any agents or do anything with the app. I pulled the latest codebase and get this same error
> 
> ```
> 2023-05-10 12:01:01 yarn run v1.22.19
> 2023-05-10 12:01:01 $ next start
> 2023-05-10 12:01:02 ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> 2023-05-10 12:01:07 Promise { <pending> }
> 2023-05-10 12:01:07 (node:29) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 172.26.0.2:7437
> 2023-05-10 12:01:07     at Function.AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
> 2023-05-10 12:01:07     at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:591:25)
> 2023-05-10 12:01:07     at RedirectableRequest.emit (events.js:400:28)
> 2023-05-10 12:01:07     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
> 2023-05-10 12:01:07     at ClientRequest.emit (events.js:400:28)
> 2023-05-10 12:01:07     at Socket.socketErrorListener (_http_client.js:475:9)
> 2023-05-10 12:01:07     at Socket.emit (events.js:400:28)
> 2023-05-10 12:01:07     at emitErrorNT (internal/streams/destroy.js:106:8)
> 2023-05-10 12:01:07     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
> 2023-05-10 12:01:07     at processTicksAndRejections (internal/process/task_queues.js:82:21)
> 2023-05-10 12:01:07 (Use `node --trace-warnings ...` to show where the warning was created)
> 2023-05-10 12:01:07 (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
> 2023-05-10 12:01:07 (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```
> 
> another example
> 
> ```
> 2023-05-10 11:33:52     at processTicksAndRejections (internal/process/task_queues.js:82:21)
> 2023-05-10 11:33:52 (Use `node --trace-warnings ...` to show where the warning was created)
> 2023-05-10 11:33:52 (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
> 2023-05-10 11:33:52 (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```
> 
> I'm on windows, tried lates main, latest tagged beta and https://github.com/Josh-XT/Agent-LLM/releases/tag/v1.1.1-alpha. all 3 with the same error. ty
> 
> Any suggestions?

Okay, it seems like I'm not the only one experiencing this error. It looks like the author doesn't have time to fix this issue at the moment.

**Comment by shaiss** [comment]
@Setmaster any chance we can reopen this issue and address it?   It seems to be a cold stop for some, inc myself.  TY for the help!

**Comment by Josh-XT** [comment]
> 

This is a front end issue, all front end issues should be in the front end repository -> https://github.com/JamesonRGrieve/Agent-LLM-Frontend

**Comment by Josh-XT** [comment]
Also, a ton of changes have happened to the back end since this issue a week ago, if you have a new issue related to the back end, please post it separetely.
