### ISSUE TITLE
Provider: Bing - coroutine 'AIProvider.instruct' was never awaited

### ISSUE THREAD

**Issue by TroublesInParadise** [Josh-XT/Agent-LLM#20]
127.0.0.1 - - [20/Apr/2023 13:03:33] "POST /api/task/start/default HTTP/1.1" 200 -
| Thinking...Response: <coroutine object AIProvider.instruct at 0x000002B709149770>

*****EXECUTION AGENT*****

1: Develop an initial task list.

*****RESPONSE*****

<coroutine object AIProvider.instruct at 0x000002B709149770>
['Execution agent response: <coroutine object AIProvider.instruct at 0x000002B709149770>']
Exception in thread Thread-17 (run):
Traceback (most recent call last):
  File "C:\Users\Stephan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Stephan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\babyagi.py", line 191, in run
    task = self.execute_next_task()
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\babyagi.py", line 165, in execute_next_task
    new_tasks = self.task_creation_agent(
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\babyagi.py", line 89, in task_creation_agent
    response = self.prompter.run(prompt, commands_enabled=False)
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\AgentLLM.py", line 70, in run
    self.response = " ".join(responses)
TypeError: sequence item 0: expected str instance, coroutine found
C:\Users\Stephan\AppData\Local\Programs\Python\Python310\lib\threading.py:1018: RuntimeWarning: coroutine 'AIProvider.instruct' was never awaited
  self._invoke_excepthook(self)

No idea what this means. Was using Ooba and it worked fine, removed the URI and changed provider/model to bing.

**Comment by Josh-XT** [comment]
Please try again if you get a chance. Last merge may have fixed this.

**Comment by Sdssourcing** [comment]
#

**Comment by Sdssourcing** [comment]
/

**Comment by Sdssourcing** [comment]
//

**Comment by TroublesInParadise** [comment]
> Please try again if you get a chance. Last merge may have fixed this.

Exception in thread Thread-19 (run):
127.0.0.1 - - [21/Apr/2023 05:50:13] "POST /api/task/start/Azimuth HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:\Users\Stephan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Stephan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\babyagi.py", line 164, in run
    task = self.execute_next_task()
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\babyagi.py", line 138, in execute_next_task
    self.response = self.execution_agent(self.primary_objective, this_task_name, this_task_id)
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\babyagi.py", line 97, in execution_agent
    prompt = prompt.replace("{COMMANDS}", "".join(self.commands))
TypeError: sequence item 0: expected str instance, dict found

This seems to happen for everything now. I've done "git restore ." twice to make sure I wasn't going crazy.




> //

You alright?

**Comment by Josh-XT** [comment]
> 

Try again with the latest pull.

**Comment by TroublesInParadise** [comment]
Exception in thread Thread-22 (run):
Traceback (most recent call last):
  File "C:\Users\Stephan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Stephan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\babyagi.py", line 176, in run
    task = self.execute_next_task()
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\babyagi.py", line 150, in execute_next_task
    self.response = self.execution_agent(self.primary_objective, this_task_name, this_task_id)
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\babyagi.py", line 117, in execution_agent
    self.response = self.prompter.run(prompt)
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\AgentLLM.py", line 72, in run
    self.response = self.instruct(prompt)
  File "C:\Users\Stephan\Desktop\Vicuna\Agent-LLM\provider\bing.py", line 42, in instruct
    with websockets.connect(self.wss_link, ssl=ssl.create_default_context()) as websocket:
  File "C:\Users\Stephan\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 478, in __init__
    loop = asyncio.get_event_loop()
  File "C:\Users\Stephan\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-22 (run)'.

Just to be sure I've run ooba and it checks out with other models, it's just a Bing thing

**Comment by Josh-XT** [comment]
Closing this issue, Bing is probably not going to work out without a lot of effort on a constant basis due to how they're trying (successfully) to make it difficult to scrape and use consistently.  I'll explore again in the future or let someone put in a pull request of a working Bing provider if they'd like.
