### ISSUE TITLE
Instruct error

### ISSUE THREAD

**Issue by timuryunuk2023** [Josh-XT/Agent-LLM#210]
### Description

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-1.1.3-alpha/app.py", line 197, in instruct
    response = agent.run(
               ^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-1.1.3-alpha/AgentLLM.py", line 99, in run
    instruction_prompt = self.INSTRUCT_PROMPT
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AgentLLM' object has no attribute 'INSTRUCT_PROMPT'
<img width="1392" alt="Знімок екрана 2023-05-03 о 13 35 34" src="https://user-images.githubusercontent.com/90114599/235917600-e4295154-108f-4f35-a041-3d291d865900.png">

### Steps to Reproduce the Bug

1. Start back and front ends
2. Go to the agent page
3. Write instruction (mine is Write tweet about AI)
4. Click on Instruct agent

### Expected Behavior

Instructs agent

### Actual Behavior

Throws an AttributeError: 'AgentLLM' object has no attribute 'INSTRUCT_PROMPT' error

### Operating System

- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Fixed in #207, please update.
