### ISSUE TITLE
No connection to web interface

### ISSUE THREAD

**Issue by robiwan303** [Josh-XT/Agent-LLM#214]
### Description

Accessing the web interface via 127.0.0.1:7860 does not work. The connection is refused. I am able to access it via port 3000, but when selecting a submenu ‚Network Error‘ is displayed.

### Steps to Reproduce the Bug

Access web interface in browser

### Expected Behavior

Show web interface 

### Actual Behavior

Connection refused (ping does not find the host8

### Additional Context / Screenshots

This is the docker log:

2023-05-03 16:02:46 agent-llm-frontend-1  | yarn run v1.22.19
2023-05-03 16:02:46 agent-llm-frontend-1  | $ next start
2023-05-03 16:02:46 agent-llm-frontend-1  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
2023-05-03 16:02:57 agent-llm-frontend-1  | Promise { <pending> }
2023-05-03 16:02:47 agent-llm-backend-1   | Collecting en-core-web-sm==3.5.0
2023-05-03 16:02:47 agent-llm-backend-1   |   Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (12.8 MB)
2023-05-03 16:02:48 agent-llm-backend-1   |      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 25.6 MB/s eta 0:00:00
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: spacy<3.6.0,>=3.5.0 in /usr/local/lib/python3.10/site-packages (from en-core-web-sm==3.5.0) (3.5.2)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.0.12)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.0.4)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.0.9)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.0.7)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.0.8)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (8.1.10)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.1.1)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.4.6)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.0.8)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: typer<0.8.0,>=0.3.0 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.7.0)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: pathy>=0.10.0 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.10.1)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (6.3.0)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (4.65.0)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.24.3)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.29.0)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.10.7)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.1.2)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (65.5.1)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (23.1)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.3.0)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (4.5.0)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.1.0)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.4)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.26.15)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2022.12.7)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/site-packages (from thinc<8.2.0,>=8.1.8->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.7.9)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/site-packages (from thinc<8.2.0,>=8.1.8->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.0.4)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/site-packages (from typer<0.8.0,>=0.3.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (8.1.3)
2023-05-03 16:02:48 agent-llm-backend-1   | Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/site-packages (from jinja2->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.1.2)
2023-05-03 16:02:49 agent-llm-backend-1   | Installing collected packages: en-core-web-sm
2023-05-03 16:02:49 agent-llm-backend-1   | Successfully installed en-core-web-sm-3.5.0
2023-05-03 16:02:49 agent-llm-backend-1   | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2023-05-03 16:02:49 agent-llm-backend-1   | INFO:     Started server process [7]
2023-05-03 16:02:49 agent-llm-backend-1   | INFO:     Waiting for application startup.
2023-05-03 16:02:49 agent-llm-backend-1   | INFO:     Application startup complete.
2023-05-03 16:02:49 agent-llm-backend-1   | INFO:     Uvicorn running on http://0.0.0.0:7437 (Press CTRL+C to quit)
2023-05-03 16:02:57 agent-llm-backend-1   | Downloading spacy model...
2023-05-03 16:02:57 agent-llm-backend-1   | ✔ Download and installation successful
2023-05-03 16:02:57 agent-llm-backend-1   | You can now load the package via spacy.load('en_core_web_sm')
2023-05-03 16:02:57 agent-llm-backend-1   | INFO:     172.19.0.3:53528 - "GET /api/provider HTTP/1.1" 200 OK
2023-05-03 16:02:57 agent-llm-backend-1   | INFO:     172.19.0.1:39636 - "GET /api/provider HTTP/1.1" 200 OK
2023-05-03 16:03:08 agent-llm-backend-1   | INFO:     172.19.0.1:47792 - "GET /api/provider HTTP/1.1" 200 OK
2023-05-03 16:03:09 agent-llm-backend-1   | INFO:     172.19.0.1:47792 - "GET /api/provider HTTP/1.1" 200 OK
2023-05-03 16:03:09 agent-llm-backend-1   | INFO:     172.19.0.1:47798 - "GET /api/agent HTTP/1.1" 200 OK
2023-05-03 16:03:10 agent-llm-backend-1   | INFO:     172.19.0.1:47798 - "GET /api/provider HTTP/1.1" 200 OK
2023-05-03 16:03:10 agent-llm-backend-1   | Failed to import pyllamacpp.
2023-05-03 16:03:10 agent-llm-backend-1   | INFO:     172.19.0.1:47798 - "GET /api/agent/Test%20Agent HTTP/1.1" 500 Internal Server Error
2023-05-03 16:03:10 agent-llm-backend-1   | ERROR:    Exception in ASGI application
2023-05-03 16:03:10 agent-llm-backend-1   | Traceback (most recent call last):
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
2023-05-03 16:03:10 agent-llm-backend-1   |     result = await app(  # type: ignore[func-returns-value]
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-03 16:03:10 agent-llm-backend-1   |     return await self.app(scope, receive, send)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
2023-05-03 16:03:10 agent-llm-backend-1   |     await super().__call__(scope, receive, send)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-05-03 16:03:10 agent-llm-backend-1   |     await self.middleware_stack(scope, receive, send)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-05-03 16:03:10 agent-llm-backend-1   |     raise exc
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-03 16:03:10 agent-llm-backend-1   |     await self.app(scope, receive, _send)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
2023-05-03 16:03:10 agent-llm-backend-1   |     await self.simple_response(scope, receive, send, request_headers=headers)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
2023-05-03 16:03:10 agent-llm-backend-1   |     await self.app(scope, receive, send)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-05-03 16:03:10 agent-llm-backend-1   |     raise exc
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-03 16:03:10 agent-llm-backend-1   |     await self.app(scope, receive, sender)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-05-03 16:03:10 agent-llm-backend-1   |     raise e
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-03 16:03:10 agent-llm-backend-1   |     await self.app(scope, receive, send)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-05-03 16:03:10 agent-llm-backend-1   |     await route.handle(scope, receive, send)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-05-03 16:03:10 agent-llm-backend-1   |     await self.app(scope, receive, send)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2023-05-03 16:03:10 agent-llm-backend-1   |     response = await func(request)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
2023-05-03 16:03:10 agent-llm-backend-1   |     raw_response = await run_endpoint_function(
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-03 16:03:10 agent-llm-backend-1   |     return await dependant.call(**values)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/app/app.py", line 182, in get_agent_config
2023-05-03 16:03:10 agent-llm-backend-1   |     agent_config = Agent(agent_name).get_agent_config()
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/app/Config/Agent.py", line 28, in __init__
2023-05-03 16:03:10 agent-llm-backend-1   |     self.PROVIDER = Provider(self.AI_PROVIDER, **self.PROVIDER_SETTINGS)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/app/provider/__init__.py", line 24, in __init__
2023-05-03 16:03:10 agent-llm-backend-1   |     self.instance = provider_class(**kwargs)
2023-05-03 16:03:10 agent-llm-backend-1   |   File "/app/provider/llamacpp.py", line 23, in __init__
2023-05-03 16:03:10 agent-llm-backend-1   |     self.model = Model(ggml_model=MODEL_PATH, n_ctx=self.MAX_TOKENS)
2023-05-03 16:03:10 agent-llm-backend-1   | NameError: name 'Model' is not defined
2023-05-03 16:03:17 agent-llm-backend-1   | INFO:     172.19.0.1:58474 - "GET /api/agent/Test%20Agent HTTP/1.1" 500 Internal Server Error
2023-05-03 16:03:17 agent-llm-backend-1   | ERROR:    Exception in ASGI application
2023-05-03 16:03:17 agent-llm-backend-1   | Traceback (most recent call last):
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
2023-05-03 16:03:17 agent-llm-backend-1   |     result = await app(  # type: ignore[func-returns-value]
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-03 16:03:17 agent-llm-backend-1   |     return await self.app(scope, receive, send)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
2023-05-03 16:03:17 agent-llm-backend-1   |     await super().__call__(scope, receive, send)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-05-03 16:03:17 agent-llm-backend-1   |     await self.middleware_stack(scope, receive, send)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-05-03 16:03:17 agent-llm-backend-1   |     raise exc
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-03 16:03:17 agent-llm-backend-1   |     await self.app(scope, receive, _send)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
2023-05-03 16:03:17 agent-llm-backend-1   |     await self.simple_response(scope, receive, send, request_headers=headers)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
2023-05-03 16:03:17 agent-llm-backend-1   |     await self.app(scope, receive, send)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-05-03 16:03:17 agent-llm-backend-1   |     raise exc
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-03 16:03:17 agent-llm-backend-1   |     await self.app(scope, receive, sender)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-05-03 16:03:17 agent-llm-backend-1   |     raise e
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-03 16:03:17 agent-llm-backend-1   |     await self.app(scope, receive, send)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-05-03 16:03:17 agent-llm-backend-1   |     await route.handle(scope, receive, send)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-05-03 16:03:17 agent-llm-backend-1   |     await self.app(scope, receive, send)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2023-05-03 16:03:17 agent-llm-backend-1   |     response = await func(request)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
2023-05-03 16:03:17 agent-llm-backend-1   |     raw_response = await run_endpoint_function(
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-03 16:03:17 agent-llm-backend-1   |     return await dependant.call(**values)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/app/app.py", line 182, in get_agent_config
2023-05-03 16:03:17 agent-llm-backend-1   |     agent_config = Agent(agent_name).get_agent_config()
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/app/Config/Agent.py", line 28, in __init__
2023-05-03 16:03:17 agent-llm-backend-1   |     self.PROVIDER = Provider(self.AI_PROVIDER, **self.PROVIDER_SETTINGS)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/app/provider/__init__.py", line 24, in __init__
2023-05-03 16:03:17 agent-llm-backend-1   |     self.instance = provider_class(**kwargs)
2023-05-03 16:03:17 agent-llm-backend-1   |   File "/app/provider/llamacpp.py", line 23, in __init__
2023-05-03 16:03:17 agent-llm-backend-1   |     self.model = Model(ggml_model=MODEL_PATH, n_ctx=self.MAX_TOKENS)
2023-05-03 16:03:17 agent-llm-backend-1   | NameError: name 'Model' is not defined
2023-05-03 16:03:43 agent-llm-backend-1   | INFO:     Shutting down
2023-05-03 16:03:43 agent-llm-backend-1   | INFO:     Waiting for application shutdown.
2023-05-03 16:03:43 agent-llm-backend-1   | INFO:     Application shutdown complete.
2023-05-03 16:03:43 agent-llm-backend-1   | INFO:     Finished server process [7]

### Operating System

- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by robiwan303** [comment]
Regarding the docker log, I think the problems starts here:

2023-05-03 16:44:38 agent-llm-backend-1   | Failed to import pyllamacpp.
2023-05-03 16:44:38 agent-llm-backend-1   | INFO:     172.20.0.1:54196 - "GET /api/agent/Test%20Agent HTTP/1.1" 500 Internal Server Error
2023-05-03 16:44:38 agent-llm-backend-1   | ERROR:    Exception in ASGI application
2023-05-03 16:44:38 agent-llm-backend-1   | Traceback (most recent call last):
2023-05-03 16:44:38 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi

**Comment by Josh-XT** [comment]
> Regarding the docker log, I think the problems starts here:
> 
> 2023-05-03 16:44:38 agent-llm-backend-1 | Failed to import pyllamacpp. 2023-05-03 16:44:38 agent-llm-backend-1 | INFO: 172.20.0.1:54196 - "GET /api/agent/Test%20Agent HTTP/1.1" 500 Internal Server Error 2023-05-03 16:44:38 agent-llm-backend-1 | ERROR: Exception in ASGI application 2023-05-03 16:44:38 agent-llm-backend-1 | Traceback (most recent call last): 2023-05-03 16:44:38 agent-llm-backend-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi

Correct, please see README instructions for Mac users.

https://github.com/Josh-XT/Agent-LLM#running-a-mac
