### ISSUE TITLE
Error on frontend

### ISSUE THREAD

**Issue by timuryunuk2023** [Josh-XT/Agent-LLM#228]
### Description

When I start frontend this error appears
error - unhandledRejection: Error: connect ECONNREFUSED ::1:7437
    at AxiosError.from (file:///Users/timur/Downloads/Agent-LLM-main/frontend/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///Users/timur/Downloads/Agent-LLM-main/frontend/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/Users/timur/Downloads/Agent-LLM-main/frontend/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}
Promise { <pending> }
{
  mutate: [Function (anonymous)],
  data: [Getter],
  error: [Getter],
  isValidating: [Getter],
  isLoading: [Getter]
}
error - unhandledRejection: Error: connect ECONNREFUSED ::1:7437
    at AxiosError.from (file:///Users/timur/Downloads/Agent-LLM-main/frontend/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///Users/timur/Downloads/Agent-LLM-main/frontend/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/Users/timur/Downloads/Agent-LLM-main/frontend/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}
Backend and frontend are working normally

### Steps to Reproduce the Bug

1. Start backend
2. Start frontend
3. Go to the agent page

### Expected Behavior

No errors

### Actual Behavior

This error occurs. 

### Operating System

- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by ZachZuk** [comment]
This exact same thing is happening to me using huggingchat and windows 11.

**Comment by Josh-XT** [comment]
https://github.com/JamesonRGrieve/Agent-LLM-Frontend

Please direct front end issues to the front end repository.
