### ISSUE TITLE
cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by Mirddinhell** [Josh-XT/Agent-LLM#250]
### Description

```
`2023-05-08 20:37:51 agent-llm-backend-1   | INFO:     172.18.0.1:57610 - "POST /api/agent/test/chat HTTP/1.1" 500 Internal Server Error
2023-05-08 20:37:51 agent-llm-backend-1   | ERROR:    Exception in ASGI application
2023-05-08 20:37:51 agent-llm-backend-1   | Traceback (most recent call last):
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
2023-05-08 20:37:51 agent-llm-backend-1   |     result = await app(  # type: ignore[func-returns-value]
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-08 20:37:51 agent-llm-backend-1   |     return await self.app(scope, receive, send)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
2023-05-08 20:37:51 agent-llm-backend-1   |     await super().__call__(scope, receive, send)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-05-08 20:37:51 agent-llm-backend-1   |     await self.middleware_stack(scope, receive, send)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-05-08 20:37:51 agent-llm-backend-1   |     raise exc
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-08 20:37:51 agent-llm-backend-1   |     await self.app(scope, receive, _send)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
2023-05-08 20:37:51 agent-llm-backend-1   |     await self.simple_response(scope, receive, send, request_headers=headers)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
2023-05-08 20:37:51 agent-llm-backend-1   |     await self.app(scope, receive, send)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-05-08 20:37:51 agent-llm-backend-1   |     raise exc
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-08 20:37:51 agent-llm-backend-1   |     await self.app(scope, receive, sender)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-05-08 20:37:51 agent-llm-backend-1   |     raise e
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-08 20:37:51 agent-llm-backend-1   |     await self.app(scope, receive, send)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-05-08 20:37:51 agent-llm-backend-1   |     await route.handle(scope, receive, send)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-05-08 20:37:51 agent-llm-backend-1   |     await self.app(scope, receive, send)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2023-05-08 20:37:51 agent-llm-backend-1   |     response = await func(request)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
2023-05-08 20:37:51 agent-llm-backend-1   |     raw_response = await run_endpoint_function(
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-08 20:37:51 agent-llm-backend-1   |     return await dependant.call(**values)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/app/app.py", line 208, in chat
2023-05-08 20:37:51 agent-llm-backend-1   |     agent = AgentLLM(agent_name)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/app/AgentLLM.py", line 46, in __init__
2023-05-08 20:37:51 agent-llm-backend-1   |     self.chroma_client = chromadb.Client(
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 83, in Client
2023-05-08 20:37:51 agent-llm-backend-1   |     return chromadb.api.local.LocalAPI(settings, get_db(settings), telemetry_client)
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 44, in get_db
2023-05-08 20:37:51 agent-llm-backend-1   |     import chromadb.db.duckdb
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 2, in <module>
2023-05-08 20:37:51 agent-llm-backend-1   |     from chromadb.db.clickhouse import (
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 3, in <module>
2023-05-08 20:37:51 agent-llm-backend-1   |     from chromadb.db.index.hnswlib import Hnswlib, delete_all_indexes
2023-05-08 20:37:51 agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 6, in <module>
2023-05-08 20:37:51 agent-llm-backend-1   |     import hnswlib
2023-05-08 20:37:51 agent-llm-backend-1   | ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block`
```

### Steps to Reproduce the Bug

Just Message to agent

### Expected Behavior

.

### Actual Behavior

.

### Operating System

- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Try this:

```
docker-compose down
git pull
docker-compose up --d
```

**Comment by Mirddinhell** [comment]
Didn't help.
