### ISSUE TITLE
TypeError: sequence item 3: expected str instance, list found

### ISSUE THREAD

**Issue by med4u** [Josh-XT/Agent-LLM#251]
### Description

When starting a new task:

=== Console output:

Executing task 1: Develop a task list.

Exception in thread Thread-2 (run_task):
Traceback (most recent call last):
  File "/home/brice/miniconda3/envs/agent/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/brice/miniconda3/envs/agent/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/brice/Agent-LLM/AgentLLM.py", line 369, in run_task
    result = self.run(task=task["task_name"], prompt="execute")
  File "/home/brice/Agent-LLM/AgentLLM.py", line 154, in run
    formatted_prompt, unformatted_prompt = self.format_prompt(
  File "/home/brice/Agent-LLM/AgentLLM.py", line 133, in format_prompt
    formatted_prompt = self.custom_format(
  File "/home/brice/Agent-LLM/AgentLLM.py", line 106, in custom_format
    return re.sub(pattern, replace, string)
  File "/home/brice/miniconda3/envs/agent/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 3: expected str instance, list found
INFO:     127.0.0.1:59044 - "GET /api/agent/Vicuna/task/status HTTP/1.1" 200 OK

### Steps to Reproduce the Bug

Ubuntu 22.04
Conda environment with python 3.10
No docker
 
Launch backend with python app.py
& frontend with yarn run dev

Create a new Agent, Oobabooga, and launch a task

### Expected Behavior

No error 

### Actual Behavior

Exception on console:

Executing task 1: Develop a task list.

Exception in thread Thread-2 (run_task):
Traceback (most recent call last):
  File "/home/brice/miniconda3/envs/agent/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/brice/miniconda3/envs/agent/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/brice/Agent-LLM/AgentLLM.py", line 369, in run_task
    result = self.run(task=task["task_name"], prompt="execute")
  File "/home/brice/Agent-LLM/AgentLLM.py", line 154, in run
    formatted_prompt, unformatted_prompt = self.format_prompt(
  File "/home/brice/Agent-LLM/AgentLLM.py", line 133, in format_prompt
    formatted_prompt = self.custom_format(
  File "/home/brice/Agent-LLM/AgentLLM.py", line 106, in custom_format
    return re.sub(pattern, replace, string)
  File "/home/brice/miniconda3/envs/agent/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 3: expected str instance, list found
INFO:     127.0.0.1:59044 - "GET /api/agent/Vicuna/task/status HTTP/1.1" 200 OK

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Please pull latest and try again.
