### ISSUE TITLE
Backend TypeError Error

### ISSUE THREAD

**Issue by timuryunuk2023** [Josh-XT/Agent-LLM#272]
### Description

INFO:     127.0.0.1:50158 - "GET /api/agent/TestAgent2 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/timur/Library/Python/3.9/lib/python/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/timur/Agent-LLM/app.py", line 162, in get_agent_config
    agent_config = Agent(agent_name).get_agent_config()
  File "/Users/timur/Agent-LLM/Config/Agent.py", line 28, in __init__
    self.PROVIDER = Provider(self.AI_PROVIDER, **self.PROVIDER_SETTINGS)
  File "/Users/timur/Agent-LLM/provider/__init__.py", line 24, in __init__
    self.instance = provider_class(**kwargs)
  File "/Users/timur/Agent-LLM/provider/huggingchat.py", line 19, in __init__
    if MAX_TOKENS <= self.MAX_TOKENS_CEILING
TypeError: '<=' not supported between instances of 'str' and 'int'

### Steps to Reproduce the Bug

1. Start frond and back ends
2. Create agent
3. Select 'huggingchat' as AI provider
4. Set max tokens and AI temperature

### Expected Behavior

Settings saved correctly

### Actual Behavior

TypeError thrown

### Operating System

- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Should be fixed in #274
