### ISSUE TITLE
The System cannot find path specified 'agents' (windows venv)

### ISSUE THREAD

**Issue by InfernalDread** [Josh-XT/Agent-LLM#28]
here is the error code:

127.0.0.1 - - [21/Apr/2023 23:55:53] "GET /api/agent HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\venv\lib\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\app.py", line 52, in get
    agents = CFG.get_agents()
  File "C:\Users\Mike's PC\Documents\transfer_to_external_storage\Agent_LLM\Agent-LLM\Config.py", line 227, in get_agents
    for file in os.listdir(memories_dir):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'agents'

EDIT: Was using llamacpp as provider

**Comment by dany-on-demand** [comment]
I had the same issue, creating an agent in the frontend seemed to fix it

**Comment by InfernalDread** [comment]
> I had the same issue, creating an agent in the frontend seemed to fix it

If you don't mind, could you share the process on how you did that?
