### ISSUE TITLE
AxiosError: Network Error

### ISSUE THREAD

**Issue by MaelHan** [Josh-XT/Agent-LLM#307]
### Description

Hello,
I've installed LLM-AGENT on my PC.

When running the command **yard dev** for launching the project, i got this error.

**error** - unhandledRejection: Error: connect ECONNREFUSED ::1:7437
    at AxiosError.from (file:///F:/AGENT-LLM/Agent-LLM-Frontend/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///F:/AGENT-LLM/Agent-LLM-Frontend/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:512:28)
    at eventHandlers.<computed> (F:\AGENT-LLM\Agent-LLM-Frontend\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:512:28)
    at Socket.socketErrorListener (node:_http_client:496:9)
    at Socket.emit (node:events:512:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  **digest:**
}

![axios](https://github.com/Josh-XT/Agent-LLM/assets/45482611/5ea4fb62-0b92-4b53-b566-99028f4d7288)

### Steps to Reproduce the Bug

launching the project

### Expected Behavior

[NONE]

### Actual Behavior

error - unhandledRejection: Error: connect ECONNREFUSED ::1:7437
    at AxiosError.from (file:///F:/AGENT-LLM/Agent-LLM-Frontend/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///F:/AGENT-LLM/Agent-LLM-Frontend/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:512:28)
    at eventHandlers.<computed> (F:\AGENT-LLM\Agent-LLM-Frontend\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:512:28)
    at Socket.socketErrorListener (node:_http_client:496:9)
    at Socket.emit (node:events:512:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}

### Additional Context / Screenshots

![axios](https://github.com/Josh-XT/Agent-LLM/assets/45482611/08f1e6ad-d7ce-4703-b9e1-14ca7d965dea)

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Hello, this is a front end issue.  Please make an issue in the front end repository if there isn't already one for this.

https://github.com/JamesonRGrieve/Agent-LLM-Frontend/issues
