### ISSUE TITLE
UI is up but no response

### ISSUE THREAD

**Issue by xerhab** [Josh-XT/Agent-LLM#39]
Running Oobabooga with `python server.py --listen-port 7774 --model vicuna-7b --no-stream`
Cloned down the repo, changed the .env file to this:

```
# =========================
# INSTANCE CONFIG
# =========================
AGENT_NAME=Agent-LLM
WORKING_DIRECTORY=WORKSPACE

# =========================
# TASK SETTINGS
# =========================
OBJECTIVE=Write an engaging tweet about AI.
INITIAL_TASK=Develop an initial task list.

# =========================
# AI PROVIDER CONFIG
# =========================
AI_PROVIDER=Oobabooga
AI_MODEL=vicuna
AI_TEMPERATURE=0.5
MAX_TOKENS=2000

# =========================
# AI PROVIDER: OPENAI
# =========================
# OPENAI_API_KEY=

# =========================
# AI PROVIDER: LLAMACPP
# =========================
# MODEL_PATH=/path/to/your/models/7B/ggml-model.bin

# =========================
# AI PROVIDER: CUSTOM (e.g., Oobabooga, Fastchat, etc.)
# =========================
AI_PROVIDER_URI=http://127.0.0.1:7774

# =========================
# COMMAND EXTENSIONS
# =========================
# COMMANDS_ENABLED=True

# =========================
# MEMORY SETTINGS
# =========================
# NO_MEMORY=False
# USE_LONG_TERM_MEMORY_ONLY=False

# =========================
# BING CONVERSATION STYLE
# =========================
# BING_CONVERSATION_STYLE=creative

# =========================
# CHATGPT SETTINGS
# =========================
# CHATGPT_USERNAME=
# CHATGPT_PASSWORD=

# =========================
# EXTENSIONS: HUGGINGFACE
# =========================
# HUGGINGFACE_API_KEY=
# HUGGINGFACE_AUDIO_TO_TEXT_MODEL=facebook/wav2vec2-large-960h-lv60-self

# =========================
# EXTENSIONS: SELENIUM
# =========================
# SELENIUM_WEB_BROWSER=chrome

# =========================
# EXTENSIONS: TWITTER
# =========================
# TW_CONSUMER_KEY=my-twitter-consumer-key
# TW_CONSUMER_SECRET=my-twitter-consumer-secret
# TW_ACCESS_TOKEN=my-twitter-access-token
# TW_ACCESS_TOKEN_SECRET=my-twitter-access-token-secret

# =========================
# EXTENSIONS: GITHUB
# =========================
# GITHUB_API_KEY=
# GITHUB_USERNAME=

# =========================
# EXTENSIONS: SENDGRID
# =========================
# SENDGRID_API_KEY=
# SENDGRID_EMAIL=

# =========================
# EXTENSIONS: MICROSOFT 365
# =========================
# MICROSOFT_365_CLIENT_ID=
# MICROSOFT_365_CLIENT_SECRET=
# MICROSOFT_365_REDIRECT_URI=

# =========================
# VOICE SETTINGS
# =========================

# BrianTTS
# USE_BRIAN_TTS=True

# Mac OS
# USE_MAC_OS_TTS=False

# ElevenLabs
# ELEVENLABS_API_KEY=
# ELEVENLABS_VOICE=Josh
```

Ran `docker compose up -d --build`
Image builds and container runs. Go to localhost, (UI Is up) select the agent, none of the prompt screens work. No response, nothing happens.
Every time I click a button I get these logs in the container.

```
2023-04-22 22:03:01 [2023-04-23 02:03:01,174] ERROR in app: Exception on /api/agent/Agent-LLM/command [GET]
2023-04-22 22:03:01 Traceback (most recent call last):
2023-04-22 22:03:01   File "/usr/local/lib/python3.8/site-packages/git/__init__.py", line 89, in <module>
2023-04-22 22:03:01     refresh()
2023-04-22 22:03:01   File "/usr/local/lib/python3.8/site-packages/git/__init__.py", line 76, in refresh
2023-04-22 22:03:01     if not Git.refresh(path=path):
2023-04-22 22:03:01   File "/usr/local/lib/python3.8/site-packages/git/cmd.py", line 392, in refresh
2023-04-22 22:03:01     raise ImportError(err)
2023-04-22 22:03:01 ImportError: Bad git executable.
2023-04-22 22:03:01 The git executable must be specified in one of the following ways:
2023-04-22 22:03:01     - be included in your $PATH
2023-04-22 22:03:01     - be set via $GIT_PYTHON_GIT_EXECUTABLE
2023-04-22 22:03:01     - explicitly set via git.refresh()
2023-04-22 22:03:01 
2023-04-22 22:03:01 All git commands will error until this is rectified.
2023-04-22 22:03:01 
2023-04-22 22:03:01 This initial warning can be silenced or aggravated in the future by setting the
2023-04-22 22:03:01 $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
2023-04-22 22:03:01     - quiet|q|silence|s|none|n|0: for no warning or exception
2023-04-22 22:03:01     - warn|w|warning|1: for a printed warning
2023-04-22 22:03:01     - error|e|raise|r|2: for a raised exception
2023-04-22 22:03:01 
2023-04-22 22:03:01 Example:
2023-04-22 22:03:01     export GIT_PYTHON_REFRESH=quiet
2023-04-22 22:03:01 
2023-04-22 22:03:01 
2023-04-22 22:03:01 The above exception was the direct cause of the following exception:
2023-04-22 22:03:01 
2023-04-22 22:03:01 Traceback (most recent call last):
2023-04-22 22:03:01   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023-04-22 22:03:01     rv = self.dispatch_request()
2023-04-22 22:03:01   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
2023-04-22 22:03:01     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-22 22:03:01   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-22 22:03:01     resp = resource(*args, **kwargs)
2023-04-22 22:03:01   File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 107, in view
2023-04-22 22:03:01     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-22 22:03:01   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-22 22:03:01     resp = meth(*args, **kwargs)
2023-04-22 22:03:01   File "/app/app.py", line 86, in get
2023-04-22 22:03:01     commands = Commands(agent_name)
2023-04-22 22:03:01   File "/app/Commands.py", line 10, in __init__
2023-04-22 22:03:01     self.commands = self.load_commands()
2023-04-22 22:03:01   File "/app/Commands.py", line 39, in load_commands
2023-04-22 22:03:01     module = importlib.import_module(f"commands.{module_name}")
2023-04-22 22:03:01   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2023-04-22 22:03:01     return _bootstrap._gcd_import(name[level:], package, level)
2023-04-22 22:03:01   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2023-04-22 22:03:01   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2023-04-22 22:03:01   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2023-04-22 22:03:01   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2023-04-22 22:03:01   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2023-04-22 22:03:01   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2023-04-22 22:03:01   File "/app/commands/github.py", line 1, in <module>
2023-04-22 22:03:01     import git
2023-04-22 22:03:01   File "/usr/local/lib/python3.8/site-packages/git/__init__.py", line 91, in <module>
2023-04-22 22:03:01     raise ImportError("Failed to initialize: {0}".format(exc)) from exc
2023-04-22 22:03:01 ImportError: Failed to initialize: Bad git executable.
2023-04-22 22:03:01 The git executable must be specified in one of the following ways:
2023-04-22 22:03:01     - be included in your $PATH
2023-04-22 22:03:01     - be set via $GIT_PYTHON_GIT_EXECUTABLE
2023-04-22 22:03:01     - explicitly set via git.refresh()
2023-04-22 22:03:01 
2023-04-22 22:03:01 All git commands will error until this is rectified.
2023-04-22 22:03:01 
2023-04-22 22:03:01 This initial warning can be silenced or aggravated in the future by setting the
2023-04-22 22:03:01 $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
2023-04-22 22:03:01     - quiet|q|silence|s|none|n|0: for no warning or exception
2023-04-22 22:03:01     - warn|w|warning|1: for a printed warning
2023-04-22 22:03:01     - error|e|raise|r|2: for a raised exception
2023-04-22 22:03:01 
2023-04-22 22:03:01 Example:
2023-04-22 22:03:01     export GIT_PYTHON_REFRESH=quiet
2023-04-22 22:03:01
```

**Comment by msl2246** [comment]
![image](https://user-images.githubusercontent.com/130526665/233818999-e3ae0624-408c-4f0e-9d6c-1f062df41217.png)

you need install 'git' in wsl2 docker terminal. then i got resolved that error

try this:
apt update
apt install git     
(and yes)

but, another error is came out. i hope someone find out how to fix.
![image](https://user-images.githubusercontent.com/130526665/233819059-e66c9f95-28a9-4b2f-88d6-5f3f0c716575.png)

**Comment by Josh-XT** [comment]
Just merged a PR that fixes this. #38
