### ISSUE TITLE
Error while setting up Agent-LLM while using docker

### ISSUE THREAD

**Issue by DavidTrack** [Josh-XT/Agent-LLM#45]
Hi, i've tried to set up this repo using the following docker commands:
docker run -it --pull always -p 80:3000 --env-file=.env ghcr.io/josh-xt/agent-llm-frontend:main
docker run -it --pull always -p 5000:5000 --env-file=.env ghcr.io/josh-xt/agent-llm-backend:main

but after running the front end container successfully i encountered a problem with the backend container , this is the output

```
F:\PROGRAMMI\IA\Agent-LLM>docker run -it --pull always -p 5000:5000 --env-file=.env ghcr.io/josh-xt/agent-llm-backend:main
main: Pulling from josh-xt/agent-llm-backend
9fbefa337077: Already exists
a25702e0699e: Already exists
3ae62d6907d0: Already exists
10b9ec96af43: Already exists
b68090968714: Already exists
f5ca1d91b2e1: Pull complete
cb7a5fdd2de1: Pull complete
becde6fef018: Pull complete
4aede630fe8c: Pull complete
d3baa4641d0a: Pull complete
493a6b3000ca: Pull complete
b1c964b400a8: Pull complete
f7d12b198864: Pull complete
21a22c754d8f: Pull complete
b7efc98f926b: Pull complete
Digest: sha256:f0156d96ef47bc0bf0c18da81bb2738b2389e280f66b98960fd548af4fc26ff0
Status: Downloaded newer image for ghcr.io/josh-xt/agent-llm-backend:main
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/app.py", line 72, in <module>
    async def add_agent(agent_name: AgentName) -> dict[str, str]:
TypeError: 'type' object is not subscriptable

```
![immagine](https://user-images.githubusercontent.com/33979484/233831477-37d5077d-a60e-403c-a6b5-9139de357bbd.png)

I pulled the latest commit and then run the docker commands.
Yesterday  I encountered a similar problem while running the repo using alternative setup.

**Comment by dangelo352** [comment]
i got the same thing and even after I got it working by importing Dict the front and back end are both running but the chat doesn't work and its basically unusable. Been trying all night to fix this

**Comment by alexl83** [comment]
Pulled latest git but backend container is crashing, here some logs
```

Attaching to agent-llm_frontend_1, agent-llm_backend_1
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/bin/uvicorn", line 8, in <module>
backend_1   |     sys.exit(main())
backend_1   |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
backend_1   |     return self.main(*args, **kwargs)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
backend_1   |     rv = self.invoke(ctx)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
backend_1   |     return ctx.invoke(self.callback, **ctx.params)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
backend_1   |     return __callback(*args, **kwargs)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 403, in main
backend_1   |     run(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 568, in run
backend_1   |     server.run()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 59, in run
backend_1   |     return asyncio.run(self.serve(sockets=sockets))
backend_1   |   File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
backend_1   |     return loop.run_until_complete(main)
backend_1   |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 66, in serve
backend_1   |     config.load()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 471, in load
backend_1   |     self.loaded_app = import_from_string(self.app)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
backend_1   |     module = importlib.import_module(module_str)
backend_1   |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
backend_1   |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1   |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
backend_1   |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
backend_1   |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
backend_1   |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
backend_1   |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
backend_1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
backend_1   |   File "/app/app.py", line 72, in <module>
backend_1   |     async def add_agent(agent_name: AgentName) -> dict[str, str]:
backend_1   | TypeError: 'type' object is not subscriptable
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/bin/uvicorn", line 8, in <module>
backend_1   |     sys.exit(main())
backend_1   |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
backend_1   |     return self.main(*args, **kwargs)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
backend_1   |     rv = self.invoke(ctx)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
backend_1   |     return ctx.invoke(self.callback, **ctx.params)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
backend_1   |     return __callback(*args, **kwargs)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 403, in main
backend_1   |     run(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 568, in run
backend_1   |     server.run()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 59, in run
backend_1   |     return asyncio.run(self.serve(sockets=sockets))
backend_1   |   File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
backend_1   |     return loop.run_until_complete(main)
backend_1   |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 66, in serve
backend_1   |     config.load()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 471, in load
backend_1   |     self.loaded_app = import_from_string(self.app)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
backend_1   |     module = importlib.import_module(module_str)
backend_1   |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
backend_1   |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1   |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
backend_1   |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
backend_1   |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
backend_1   |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
backend_1   |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
backend_1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
backend_1   |   File "/app/app.py", line 72, in <module>
backend_1   |     async def add_agent(agent_name: AgentName) -> dict[str, str]:
backend_1   | TypeError: 'type' object is not subscriptable
```

**Comment by DamonianoStudios** [comment]
I'm getting the same issue, currently my only way around it is to run the backend through the `python app.py` command, which isn't ideal as I don't think the container is doing its job at that point.

**Comment by Josh-XT** [comment]
Sorry folks! I have this planned to be fixed today. It looks like it doesn't like some of the response models that were added when switching to FastAPI.

**Comment by Josh-XT** [comment]
Give it another try with the docker-compose. It should work now.

**Comment by DavidTrack** [comment]
It seems to be not working.
This is that i did , in order:
1. pulled latest commit
2. docker compose command from the homepage 
3.ran my oobagooba interface with Vicuna with this command ```python server.py  --model vicuna-13b-GPTQ-4bit-128g --listen --no-stream --auto-devices --xformers```
this is my .env file:
```
AI_PROVIDER=oobabooga
AI_PROVIDER_URI=http://localhost:7860
AI_MODEL=vicuna
AI_TEMPERATURE=0.2
MAX_TOKENS=2096
```
This is the output of the console running vicuna :
```
Starting agent...
Gradio HTTP request redirected to localhost :)
Loading vicuna-13b-GPTQ-4bit-128g...
Found the following quantized model: models\vicuna-13b-GPTQ-4bit-128g\vicuna-13b-4bit-128g.safetensors
Loading model ...
Done.
Loaded the model in 19.74 seconds.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```
4. opened http://localhost/ to see the homepage of agentLLM and tried to instruct agentLLM but it didn't work

This is the error that appears in the docker log for the backend image:
```
2023-04-23 17:58:21 Traceback (most recent call last):
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
2023-04-23 17:58:21     result = await app(  # type: ignore[func-returns-value]
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-04-23 17:58:21     return await self.app(scope, receive, send)
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
2023-04-23 17:58:21     await super().__call__(scope, receive, send)
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-04-23 17:58:21     await self.middleware_stack(scope, receive, send)
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-04-23 17:58:21     raise exc
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-04-23 17:58:21     await self.app(scope, receive, _send)
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
2023-04-23 17:58:21     await self.simple_response(scope, receive, send, request_headers=headers)
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
2023-04-23 17:58:21     await self.app(scope, receive, send)
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-04-23 17:58:21     raise exc
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-04-23 17:58:21     await self.app(scope, receive, sender)
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-04-23 17:58:21     raise e
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-04-23 17:58:21     await self.app(scope, receive, send)
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-04-23 17:58:21     await route.handle(scope, receive, send)
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-04-23 17:58:21     await self.app(scope, receive, send)
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2023-04-23 17:58:21     response = await func(request)
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
2023-04-23 17:58:21     raw_response = await run_endpoint_function(
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-04-23 17:58:21     return await dependant.call(**values)
2023-04-23 17:58:21   File "/app/app.py", line 127, in get_commands
2023-04-23 17:58:21     commands = Commands(agent_name)
2023-04-23 17:58:21   File "/app/Commands.py", line 10, in __init__
2023-04-23 17:58:21     self.commands = self.load_commands()
2023-04-23 17:58:21   File "/app/Commands.py", line 39, in load_commands
2023-04-23 17:58:21     module = importlib.import_module(f"commands.{module_name}")
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-04-23 17:58:21     return _bootstrap._gcd_import(name[level:], package, level)
2023-04-23 17:58:21   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-04-23 17:58:21   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-04-23 17:58:21   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-04-23 17:58:21   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-04-23 17:58:21   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-04-23 17:58:21   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-04-23 17:58:21   File "/app/commands/github.py", line 1, in <module>
2023-04-23 17:58:21     import git
2023-04-23 17:58:21   File "/usr/local/lib/python3.10/site-packages/git/__init__.py", line 91, in <module>
2023-04-23 17:58:21     raise ImportError("Failed to initialize: {0}".format(exc)) from exc
2023-04-23 17:58:21 ImportError: Failed to initialize: Bad git executable.
2023-04-23 17:58:21 The git executable must be specified in one of the following ways:
2023-04-23 17:58:21     - be included in your $PATH
2023-04-23 17:58:21     - be set via $GIT_PYTHON_GIT_EXECUTABLE
2023-04-23 17:58:21     - explicitly set via git.refresh()
2023-04-23 17:58:21 
2023-04-23 17:58:21 All git commands will error until this is rectified.
2023-04-23 17:58:21 
2023-04-23 17:58:21 This initial warning can be silenced or aggravated in the future by setting the
2023-04-23 17:58:21 $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
2023-04-23 17:58:21     - quiet|q|silence|s|none|n|0: for no warning or exception
2023-04-23 17:58:21     - warn|w|warning|1: for a printed warning
2023-04-23 17:58:21     - error|e|raise|r|2: for a raised exception
2023-04-23 17:58:21 
2023-04-23 17:58:21 Example:
2023-04-23 17:58:21     export GIT_PYTHON_REFRESH=quiet
2023-04-23 17:58:21 
```
