### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'EXECUTION_PROMPT'

### ISSUE THREAD

**Issue by OverwriteDev** [Josh-XT/Agent-LLM#55]
Running local, the latest pull kicks up this error when providing the agent with an objective:

```
INFO:     127.0.0.1:59750 - "OPTIONS /api/agent/Bob/task HTTP/1.1" 200 OK
Using embedded DuckDB with persistence: data will be stored in: agents/default/memories
Exception in thread INFO:     127.0.0.1:59750 - "POST /api/agent/Bob/task HTTP/1.1" 200 OK
Thread-7 (run_task):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    INFO:     127.0.0.1:59750 - "GET /api/agent/Bob/task/status HTTP/1.1" 200 OK
self._target(*self._args, **self._kwargs)
  File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 282, in run_task
    task = self.execute_next_task()
  File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 257, in execute_next_task
    self.response = self.execution_agent(self.primary_objective, this_task_name, this_task_id)
  File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 202, in execution_agent
INFO:     127.0.0.1:59750 - "GET /api/agent HTTP/1.1" 200 OK
    prompt = self.CFG.EXECUTION_PROMPT
AttributeError: 'Config' object has no attribute 'EXECUTION_PROMPT
```

**Comment by Josh-XT** [comment]
What is your AI_MODEL set to?

**Comment by OverwriteDev** [comment]
It's set to vicuna.

**Comment by Josh-XT** [comment]
If you're running locally, please pull main and test again.
