### ISSUE TITLE
TypeError: AgentLLM.update_output_list() missing 1 required positional argument: 'output'

### ISSUE THREAD

**Issue by OverwriteDev** [Josh-XT/Agent-LLM#58]
Running oobabooga local with vicuna as the model with the latest pull. I can create an agent, set it's objective and get a response back but at some point this error pops up and the agent just loops task over and over.
```
Exception in thread Thread-6 (run_task):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 282, in run_task
    task = self.execute_next_task()
  File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 257, in execute_next_task
    self.response = self.execution_agent(self.primary_objective, this_task_name, this_task_id)
  File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 229, in execution_agent
    self.update_output_list(f"Execution agent response:\n\n{self.response}")
TypeError: AgentLLM.update_output_list() missing 1 required positional argument: 'output'
```

**Comment by Josh-XT** [comment]
I believe solved by #59

**Comment by OverwriteDev** [comment]
This particular error is gone now. There's a new one in its place.
```
Exception in thread Thread-6 (run_task):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 282, in run_task
    task = self.execute_next_task()
  File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 257, in execute_next_task
    self.response = self.execution_agent(self.primary_objective, this_task_name, this_task_id)
  File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 230, in execution_agent
    print(self.output_list)
AttributeError: 'AgentLLM' object has no attribute 'output_list'
```

**Comment by Josh-XT** [comment]
> This particular error is gone now. There's a new one in its place.
> 
> ```
> Exception in thread Thread-6 (run_task):
> Traceback (most recent call last):
>   File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "C:\Python310\lib\threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 282, in run_task
>     task = self.execute_next_task()
>   File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 257, in execute_next_task
>     self.response = self.execution_agent(self.primary_objective, this_task_name, this_task_id)
>   File "D:\LocalGPT\Agent-LLM\AgentLLM.py", line 230, in execution_agent
>     print(self.output_list)
> AttributeError: 'AgentLLM' object has no attribute 'output_list'
> ```

Just pushed an update to fix this.

**Comment by OverwriteDev** [comment]
Running a test now.
