### ISSUE TITLE
Agent name not found

### ISSUE THREAD

**Issue by dany-on-demand** [Josh-XT/Agent-LLM#94]
Hope it's not much of a bother reporting an obvious issue. work_with_ai is broken right now - can't even disable it through frontend. Manually deleting the .py fixes this

Using latest commit, latest frontend freshly compiled, clean directory, .env setup for ooba (nothing else changed). Whenever I click on the agent in the agent list, or try to do anything this exception gets triggered:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Daniel\anaconda3\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\Daniel\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Daniel\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Daniel\anaconda3\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Daniel\anaconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Daniel\anaconda3\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Projects\generative\llm\Agent-LLM\app.py", line 137, in get_commands
    commands = Commands(agent_name)
  File "C:\Projects\generative\llm\Agent-LLM\Commands.py", line 10, in __init__
    self.commands = self.load_commands()
  File "C:\Projects\generative\llm\Agent-LLM\Commands.py", line 41, in load_commands
    command_class = getattr(module, module_name)()
  File "C:\Projects\generative\llm\Agent-LLM\commands\work_with_ai.py", line 12, in __init__
    name = f" AI Agent {agent.name}"
AttributeError: 'dict' object has no attribute 'name'
```

**Comment by Josh-XT** [comment]
Please attempt to pull the latest and see if that is still happening.  I believe the last merge should have resolved this.
